// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppState holds the persistent state for recent history and workspace memory.
 */
export interface AppState {
    "recentFiles": RecentItem[] | null;
    "recentFolders": RecentItem[] | null;
    "recentWorkspaces": WorkspaceConfig[] | null;
    "lastWorkspace"?: WorkspaceConfig | null;
}

/**
 * FileEntry represents a file or folder in a directory.
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "extension": string;
    "childrenCount": number;
}

/**
 * RecentItem represents a recently opened file or folder.
 */
export interface RecentItem {
    "path": string;
    "name": string;
    "timestamp": string;
}

/**
 * WorkspaceConfig represents a workspace containing one or more directories.
 */
export interface WorkspaceConfig {
    "id": string;
    "name": string;
    "folders": string[] | null;
    "timestamp": string;
}
