// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides workspace and filesystem operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRecentFile adds a file to recent files.
 */
export function AddRecentFile(filePath: string): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(522549805, filePath);
}

/**
 * AddRecentFolder adds a directory to recent folders.
 */
export function AddRecentFolder(dirPath: string): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(558157239, dirPath);
}

/**
 * AddRecentWorkspace adds or updates a multi-folder workspace in recent history.
 */
export function AddRecentWorkspace(name: string, folders: string[] | null): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(2827032440, name, folders);
}

/**
 * ClearRecent clears a specific category from recent history.
 */
export function ClearRecent(category: string): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(406110637, category);
}

/**
 * GetAppState returns recent history and workspace memory from local persistent storage.
 */
export function GetAppState(): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(3090697371);
}

/**
 * OpenDirectoryDialog opens a native folder selection dialog and records recent history.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(2087742016);
}

/**
 * OpenFileDialog opens a native file selection dialog and records recent history.
 */
export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(1246820807);
}

/**
 * ReadDirectory lists immediate child directories and files inside dirPath.
 */
export function ReadDirectory(dirPath: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(4205383996, dirPath);
}

/**
 * ReadFileContent reads text content of a file (up to 1MB) for inspection/preview.
 */
export function ReadFileContent(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3951753232, filePath);
}

/**
 * RenamePath renames a file or directory on disk and updates storage if needed.
 */
export function RenamePath(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(4194463640, oldPath, newPath);
}

/**
 * SetApp allows injecting or updating the Wails application reference.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4287363202, app);
}

/**
 * WriteFileContent writes or overwrites content to a physical file on disk.
 */
export function WriteFileContent(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1391865087, filePath, content);
}
