// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ParserService from "./parserservice.js";
export {
    ParserService
};

export type {
    ASTNodeData,
    ASTSummary,
    FileASTResult
} from "./models.js";
