// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ASTNodeData represents an individual AST node for the visual canvas
 */
export interface ASTNodeData {
    "id": string;
    "kind": string;

    /**
     * "string", "number", "boolean", "string_array", "array", "object", "function", "variable", "import", "other"
     */
    "type": string;
    "key": string;
    "value": any;
    "rawText": string;
    "description"?: string;
    "startLine": number;
    "endLine": number;
    "startByte": number;
    "endByte": number;
    "children"?: ASTNodeData[] | null;
}

/**
 * ASTSummary represents the simplified AST result sent to frontend
 */
export interface ASTSummary {
    "language": string;
    "rootType": string;
    "nodeCount": number;
    "hasErrors": boolean;
    "sexpr": string;
}

/**
 * FileASTResult is the complete parsed AST response for a file
 */
export interface FileASTResult {
    "filePath": string;
    "language": string;
    "rootKind": string;
    "nodes": ASTNodeData[] | null;
    "description"?: string;
    "schemaName"?: string;
    "schemaUrl"?: string;
    "schemaProperties"?: { [_ in string]?: string } | null;
    "error"?: string;
}
