// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ParserService provides AST parsing via Tree-sitter for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close cleans up resources
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(770681058);
}

/**
 * GetPropertyDescription looks up the schema description for a given key path in a file
 */
export function GetPropertyDescription(filePath: string, keyPath: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3604348411, filePath, keyPath);
}

/**
 * LoadGrammar loads a shared library grammar (.dll/.so/.dylib) dynamically via purego
 */
export function LoadGrammar(libPath: string, langName: string): $CancellablePromise<boolean> {
    return $Call.ByID(681901079, libPath, langName);
}

/**
 * ParseCode parses source code with a loaded language grammar
 */
export function ParseCode(langName: string, sourceCode: string): $CancellablePromise<$models.ASTSummary | null> {
    return $Call.ByID(605270480, langName, sourceCode);
}

/**
 * ParseFile reads and parses a source file into structured AST nodes for Knot canvas
 */
export function ParseFile(filePath: string): $CancellablePromise<$models.FileASTResult | null> {
    return $Call.ByID(2473745407, filePath);
}

/**
 * SaveFileContent writes updated content back to the physical file on disk
 */
export function SaveFileContent(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1552259258, filePath, content);
}
