// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo contains metadata about the application and runtime environment.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "os": string;
    "arch": string;
    "goVersion": string;
}
