// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides application-level operations and information to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseWindow closes the active application window.
 */
export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(2942628841);
}

/**
 * GetAppInfo returns system and application metadata.
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(2264177560);
}

/**
 * IsWindowMaximized returns true if the active window is maximized.
 */
export function IsWindowMaximized(): $CancellablePromise<boolean> {
    return $Call.ByID(1205738195);
}

/**
 * MinimizeWindow minimizes the active application window.
 */
export function MinimizeWindow(): $CancellablePromise<void> {
    return $Call.ByID(1057758347);
}

/**
 * ToggleMaximizeWindow toggles between maximized and restored state.
 */
export function ToggleMaximizeWindow(): $CancellablePromise<void> {
    return $Call.ByID(482727773);
}
